version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/rastervision_pipeline"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/rastervision_aws_s3"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/rastervision_aws_batch"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/rastervision_core"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/rastervision_pytorch_learner"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/rastervision_pytorch_backend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/rastervision_gdal_vsi"
    schedule:
      interval: "monthly"
