sudo: required

language:
   - python

services:
   - docker

env:
   global:
      - CLEAN_TRAVIS_TAG=${TRAVIS_TAG/[[:space:]]/}
      - COMMIT=${CLEAN_TRAVIS_TAG:-${TRAVIS_COMMIT:0:7}}

script:
   - .travis/build
   - .travis/test

after_success:
   - cat src/.coverage

deploy:
   - provider: script
     script: .travis/deploy
     skip_cleanup: true
     on:
        branch: develop
   - provider: script
     script: .travis/deploy
     skip_cleanup: true
     on:
        tags: true
